max_batch_size = 256
clean_rollout_path = true

[model] 
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
max_model_len = 2048

[monitor.wandb]
project = "formatask-debug"

[data]
name = "kalomaze/general-formatask-it2"

[parallel]
dp = 4

[sampling]
temperature = 1.0
n = 16