max_batch_size = 180
clean_rollout_path = true

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
max_model_len = 16384

[data]
name = "PrimeIntellect/INTELLECT-2-only-math"

[data.difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.1
max_solve_rate = 0.5

[parallel]
dp = 6

[rl]
ckpt_path = "rollouts"
clean_ckpt_path = true

[sampling]
temperature = 1.0
n = 16
