project = "multitask-debug"

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

[train]
micro_bs = 2 # change to 8 for H200
reshard_after_forward = true

[optim]
batch_size = 128
step_per_rollout = 4
grad_norm_clip = 0.0001

[optim.optim]
lr = 5e-6

[data]
path = "rollouts"
seq_length = 2048

[ckpt]
rollout_path = "checkpoints"